[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  NODE_VERSION = "20"

# Preview deployments for all branches
[context.branch-deploy]
  command = "npm run build"

# Production builds
[context.production]
  command = "npm run build"

# Development builds
[context.dev]
  command = "npm run build"
